/* Laureate Lab data — last checked 27 Sep 2026.
   conf: "confirmed" = date published for the 2027 cycle; "typical" = date pattern from past cycles, verify before planning. */
window.LL_CHECKED = "2026-09-27";
const S = (q) => "https://www.google.com/search?q=" + encodeURIComponent(q + " official");
window.LL_SCHOLARSHIPS = [
  // ---------- GLOBAL ----------
  {id:"chevening",name:"Chevening Scholarships",host:"United Kingdom",region:"Europe",levels:["Masters"],deadline:"2026-10-06",window:"4 Aug – 6 Oct 2026, 11:00 UTC",conf:"confirmed",funding:"Full tuition, monthly stipend, flights, visa",elig:"Undergraduate degree (2:1 or equivalent), 2,800+ hours work experience, apply to 3 UK courses, return home 2 years after",url:"https://www.chevening.org/scholarship/nigeria/",ng:true,workHrs:2800,minClass:2,essays:["leadership","networking","whyuk","career"],tags:["leadership","fully funded"]},
  {id:"csc-masters",name:"Commonwealth Master's Scholarships",host:"United Kingdom",region:"Europe",levels:["Masters"],deadline:"2026-10-20",window:"CSC closes 20 Oct 2026, 16:00 GMT — national nominator deadline is earlier",conf:"confirmed",funding:"Full tuition, stipend, flights, thesis grant",elig:"Low/middle-income Commonwealth citizen; apply via national nominating body (Nigeria: Federal Scholarship Board) and CSC portal",url:"https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/",ng:true,minClass:2,essays:["impact","sop"],tags:["development","fully funded"]},
  {id:"csc-phd",name:"Commonwealth PhD Scholarships",host:"United Kingdom",region:"Europe",levels:["PhD"],deadline:"2026-10-20",window:"Usually same October window as Master's; confirm with nominator",conf:"typical",funding:"Full tuition, stipend, flights, fieldwork support",elig:"Commonwealth citizen from eligible country; 2:2 minimum (2:1 typical); research proposal with UK supervisor support",url:"https://cscuk.fcdo.gov.uk/scholarships/commonwealth-phd-scholarships/",ng:true,minClass:3,essays:["proposal","impact"],tags:["research","fully funded"]},
  {id:"gates",name:"Gates Cambridge Scholarship",host:"United Kingdom",region:"Europe",levels:["Masters","PhD"],deadline:"2026-12-08",window:"8 Dec 2026 or 6 Jan 2027 depending on course (non-US applicants)",conf:"confirmed",funding:"Full cost of study at Cambridge plus maintenance",elig:"Non-UK citizens applying to a full-time Cambridge postgraduate course; leadership + commitment to improving lives",url:"https://www.gatescambridge.org/apply/timeline/",ng:true,minClass:1,essays:["personal","sop"],tags:["elite","fully funded"]},
  {id:"knight",name:"Knight-Hennessy Scholars (Stanford)",host:"United States",region:"Americas",levels:["Masters","PhD"],deadline:"2026-10-06",window:"Early October 2026 (reported 6 Oct) — confirm on official site",conf:"confirmed",funding:"Full funding for any Stanford graduate degree",elig:"Bachelor's earned within ~7 years; separate Stanford graduate application",url:"https://knight-hennessy.stanford.edu/admission/preparing-your-applications/application-deadlines",ng:true,essays:["personal"],tags:["elite","fully funded"]},
  {id:"clarendon",name:"Clarendon Fund (Oxford)",host:"United Kingdom",region:"Europe",levels:["Masters","PhD"],deadline:"2026-12-02",window:"Your Oxford course's Dec 2026 or Jan 2027 deadline — no separate form",conf:"typical",funding:"Full fees plus living grant",elig:"Academic excellence; considered automatically when you apply to Oxford by the funding deadline",url:"https://www.ox.ac.uk/clarendon",ng:true,minClass:1,essays:["sop"],tags:["automatic","fully funded"]},
  {id:"weidenfeld",name:"Oxford Weidenfeld & Hoffmann Scholarships",host:"United Kingdom",region:"Europe",levels:["Masters"],deadline:"2027-01-07",window:"Dec 2026 – Jan 2027 (by course)",conf:"typical",funding:"Full fees, living costs, leadership programme",elig:"Citizens of eligible developing/emerging economies; commitment to return and serve",url:"https://www.weidenfeldhoffmann.org/",ng:true,essays:["leadership","impact"],tags:["leadership","fully funded"]},
  {id:"rhodes-wa",name:"Rhodes Scholarship — West Africa",host:"United Kingdom",region:"Europe",levels:["Masters","PhD"],deadline:"2026-08-27",window:"Closed 27 Aug 2026 · next round usually opens ~1 June 2027",conf:"closed",funding:"Oxford fees, stipend (≈£20k/yr), flights",elig:"Citizens of 20 West African countries incl. Nigeria; age limits apply — see Information for Candidates",url:"https://www.rhodeshouse.ox.ac.uk/scholarships/applications/west-africa/",ng:true,ageMax:24,minClass:1,essays:["personal","leadership"],tags:["elite","fully funded"]},
  {id:"schwarzman",name:"Schwarzman Scholars (Tsinghua)",host:"China",region:"Asia",levels:["Masters"],deadline:"2027-09-15",window:"Opens Apr 2027, closes Sep 2027 (Class of 2028–29)",conf:"typical",funding:"Full tuition, room, board, travel, stipend",elig:"Age 18–28 on 1 Aug of enrolment year; bachelor's degree; leadership record",url:"https://www.schwarzmanscholars.org/admissions/",ng:true,ageMax:28,essays:["leadership","personal"],tags:["leadership","fully funded"]},
  {id:"erasmus",name:"Erasmus Mundus Joint Masters",host:"European Union (2–4 countries)",region:"Europe",levels:["Masters"],deadline:"2027-01-15",window:"Most programmes Oct 2026 – Jan 2027; each sets its own date",conf:"typical",funding:"Tuition, ≈€1,400/month, travel & insurance",elig:"Bachelor's degree; apply to a specific joint programme from the catalogue",url:"https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",ng:true,essays:["motivation"],tags:["mobility","fully funded"]},
  {id:"daad-epos",name:"DAAD EPOS Development-Related Courses",host:"Germany",region:"Europe",levels:["Masters","PhD"],deadline:"2026-10-31",window:"Varies by course — many Aug–Oct 2026",conf:"typical",funding:"€992–1,300/month, insurance, travel",elig:"2+ years professional experience; development-related field; degree ≤6 years old",url:"https://www.daad.de/en/study-and-research-in-germany/scholarships/",ng:true,workHrs:3500,essays:["motivation","impact"],tags:["development","fully funded"]},
  {id:"si",name:"Swedish Institute Scholarships for Global Professionals",host:"Sweden",region:"Europe",levels:["Masters"],deadline:"2027-02-20",window:"University application by mid-Jan 2027, SI application ~Feb 2027",conf:"typical",funding:"Tuition, SEK 12,000/month, travel grant, insurance",elig:"Citizen of an eligible country (check list), 3,000+ hours leadership/work experience",url:"https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/",ng:true,workHrs:3000,essays:["leadership","impact"],tags:["leadership","fully funded"]},
  {id:"kth",name:"KTH Scholarship",host:"Sweden",region:"Europe",levels:["Masters"],deadline:"2027-01-15",window:"15 Jan 2027 with programme application",conf:"typical",funding:"Full tuition",elig:"Non-EU applicant to a KTH master's; top academic record",url:"https://www.kth.se/en/studies/master/admission/scholarships",ng:true,minClass:1,essays:["motivation"],tags:["tuition"]},
  {id:"delft",name:"Justus & Louise van Effen Excellence (TU Delft)",host:"Netherlands",region:"Europe",levels:["Masters"],deadline:"2026-12-01",window:"1 Dec 2026",conf:"typical",funding:"Tuition + €1,100/month living",elig:"Excellent non-EU MSc applicant (≈80% of max GPA)",url:"https://www.tudelft.nl/en/education/practical-matters/scholarships",ng:true,minClass:1,essays:["motivation"],tags:["fully funded"]},
  {id:"radboud",name:"Radboud Scholarship Programme",host:"Netherlands",region:"Europe",levels:["Masters"],deadline:"2027-01-31",window:"Around 1 Feb 2027 (confirm)",conf:"typical",funding:"Partial tuition waiver (reduced to ~€2,500) + some cover",elig:"Non-EU, excellent results, admitted to an English-taught master's",url:"https://www.ru.nl/en/education/scholarships-and-grants",ng:true,essays:["motivation"],tags:["partial"]},
  {id:"eth",name:"ETH Zurich Excellence Masters (ESOP)",host:"Switzerland",region:"Europe",levels:["Masters"],deadline:"2026-12-15",window:"Nov 1 – Dec 15 2026 with master's application",conf:"typical",funding:"CHF 12,000/semester + tuition waiver",elig:"Top 10% of bachelor's class",url:"https://ethz.ch/en/studies/financial/scholarships/excellencescholarship.html",ng:true,minClass:1,essays:["motivation"],tags:["elite"]},
  {id:"eiffel",name:"Eiffel Excellence Scholarship",host:"France",region:"Europe",levels:["Masters","PhD"],deadline:"2027-01-08",window:"French university nominates you — internal deadline Nov–Dec 2026",conf:"typical",funding:"€1,181/month (MSc), €1,700 (PhD), travel, insurance",elig:"Apply through a French host institution; age ≤25 (MSc) / ≤30 (PhD)",url:"https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence",ng:true,ageMax:30,essays:["motivation"],tags:["nominated"]},
  {id:"ubc-isp",name:"UBC International Scholars Program",host:"Canada",region:"Americas",levels:["Undergraduate"],deadline:"2026-11-15",window:"15 Nov 2026 (school nomination) / 1 Dec 2026",conf:"confirmed",funding:"Need- and merit-based, up to full cost",elig:"International secondary-school students; community leadership",url:"https://you.ubc.ca/financial-planning/scholarships-awards-international-students/",ng:true,essays:["personal"],tags:["undergrad"]},
  {id:"reach-oxford",name:"Reach Oxford Scholarship",host:"United Kingdom",region:"Europe",levels:["Undergraduate"],deadline:"2026-10-15",window:"UCAS 15 Oct 2026 · scholarship form ~26 Jan 2027",conf:"confirmed",funding:"Fees, living costs, one return flight",elig:"Low-income country students who can't study in their own country",url:"https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/oxford-support/reach-oxford-scholarship",ng:true,essays:["personal"],tags:["undergrad"]},
  {id:"uopeople",name:"University of the People (tuition-free)",host:"Online",region:"Online",levels:["Undergraduate","Masters"],deadline:"2026-10-22",window:"Terms roll: 22 Oct 2026, 7 Jan 2027…",conf:"confirmed",funding:"No tuition; small assessment fees (waivers available)",elig:"Secondary-school completion; English proficiency",url:"https://www.uopeople.edu/",ng:true,essays:["personal"],tags:["online","rolling"]},
  {id:"fulbright",name:"Fulbright Foreign Student Program",host:"United States",region:"Americas",levels:["Masters","PhD"],deadline:"2027-05-15",window:"Nigeria round usually Feb–May (for 2028 entry)",conf:"typical",funding:"Tuition, stipend, airfare, health cover",elig:"Nigerian citizen, bachelor's, apply via U.S. Mission Nigeria",url:"https://ng.usembassy.gov/the-fulbright-foreign-student-program/",ng:true,essays:["sop","personal"],tags:["fully funded"]},
  {id:"aauw",name:"AAUW International Fellowships (women)",host:"United States",region:"Americas",levels:["Masters","PhD"],deadline:"2026-11-15",window:"Aug 1 – Nov 15 2026",conf:"typical",funding:"$20,000–$50,000",elig:"Women who are not U.S. citizens; full-time study in the U.S.",url:"https://www.aauw.org/resources/programs/fellowships-grants/current-opportunities/international/",ng:true,essays:["personal","impact"],tags:["women"]},
  {id:"mext",name:"MEXT Japanese Government Scholarship",host:"Japan",region:"Asia",levels:["Undergraduate","Masters","PhD"],deadline:"2027-05-15",window:"Embassy track typically Apr–May 2027",conf:"typical",funding:"Tuition, ≈¥143,000–147,000/month, flights",elig:"Apply via Embassy of Japan in Nigeria; age ≤34 for research students",url:"https://www.studyinjapan.go.jp/en/planning/scholarships/mext-scholarships/",ng:true,ageMax:34,essays:["proposal"],tags:["fully funded"]},
  {id:"csc-china",name:"Chinese Government Scholarship (CSC)",host:"China",region:"Asia",levels:["Undergraduate","Masters","PhD"],deadline:"2027-03-31",window:"Typically Jan–Apr 2027 via university or embassy",conf:"typical",funding:"Tuition, housing, stipend, insurance",elig:"Non-Chinese citizen; age ≤35 (Masters) / ≤40 (PhD)",url:"https://www.campuschina.org/",ng:true,ageMax:40,essays:["proposal","sop"],tags:["fully funded"]},
  {id:"gks",name:"Global Korea Scholarship (GKS)",host:"South Korea",region:"Asia",levels:["Undergraduate","Masters","PhD"],deadline:"2027-03-15",window:"Graduate: Feb–Mar 2027 · Undergraduate: Sep–Oct",conf:"typical",funding:"Airfare, tuition, ₩1–1.5m/month, Korean language year",elig:"Under 40 (grad), GPA ≥80%",url:"https://www.studyinkorea.go.kr/",ng:true,ageMax:39,essays:["sop","proposal"],tags:["fully funded"]},
  {id:"turkiye",name:"Türkiye Bursları",host:"Türkiye",region:"Europe",levels:["Undergraduate","Masters","PhD"],deadline:"2027-02-20",window:"Typically 10 Jan – 20 Feb 2027",conf:"typical",funding:"Tuition, stipend, housing, flights, Turkish language year",elig:"Age limits (UG <21, MSc <30, PhD <35); academic thresholds",url:"https://www.turkiyeburslari.gov.tr/",ng:true,ageMax:34,essays:["motivation"],tags:["fully funded"]},
  {id:"hungaricum",name:"Stipendium Hungaricum",host:"Hungary",region:"Europe",levels:["Undergraduate","Masters","PhD"],deadline:"2027-01-15",window:"Typically Nov 2026 – mid-Jan 2027; Nigeria is a partner country",conf:"typical",funding:"Tuition, monthly stipend, housing, insurance",elig:"Nominated through your home sending partner (Nigeria: Federal Scholarship Board)",url:"https://stipendiumhungaricum.hu/",ng:true,essays:["motivation"],tags:["fully funded"]},
  {id:"mastercard",name:"Mastercard Foundation Scholars Program",host:"Africa / Canada / USA partners",region:"Africa",levels:["Undergraduate","Masters"],deadline:null,window:"Each partner university sets its own window",conf:"typical",funding:"Tuition, living, leadership training",elig:"Young Africans with financial need and commitment to give back",url:"https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/",ng:true,essays:["personal","impact"],tags:["africa"]},
  {id:"mandela-rhodes",name:"Mandela Rhodes Scholarship",host:"South Africa",region:"Africa",levels:["Masters"],deadline:"2026-04-30",window:"Closed for 2027 · next round usually opens ~March 2027",conf:"closed",funding:"Fees, accommodation, stipend, leadership programme",elig:"African citizens aged 19–29 applying to South African universities",url:"https://www.mandelarhodes.org/scholarship/apply/",ng:true,ageMax:29,essays:["leadership","personal"],tags:["africa","leadership"]},
  {id:"jjwbgsp",name:"Joint Japan / World Bank Graduate Scholarship",host:"Global (partner programmes)",region:"Global",levels:["Masters"],deadline:"2027-03-31",window:"Typically Feb–Mar for preferred programmes",conf:"typical",funding:"Tuition, stipend, travel, insurance",elig:"3+ years development experience after first degree; admitted to eligible programme",url:"https://www.worldbank.org/en/programs/scholarships",ng:true,workHrs:5000,essays:["impact","career"],tags:["development"]},

  // ---------- NIGERIA (national, corporate, state) ----------
  {id:"ptdf",name:"PTDF Overseas Postgraduate Scholarship",host:"UK, Germany, France, Malaysia",region:"Nigeria",levels:["Masters","PhD"],deadline:"2027-02-26",window:"2026/27 ran 16 Jan – 27 Feb 2026 · expect ~Jan–Feb 2027",conf:"typical",funding:"Full tuition, stipend, flights",elig:"Nigerian; oil & gas-relevant fields; 2:1 (MSc) / MSc (PhD); NYSC; admission offer",url:"https://ptdf.gov.ng/",ng:true,minClass:2,essays:["sop"],tags:["nigeria","oil & gas"],national:true},
  {id:"fsb-bea",name:"Federal Government BEA Scholarship",host:"Russia, Hungary, Morocco, Algeria, others",region:"Nigeria",levels:["Undergraduate","Masters","PhD"],deadline:null,window:"Usually announced Apr–Jun; exam-based screening",conf:"typical",funding:"Tuition & stipend from host country + FG top-up",elig:"Nigerian; strong WAEC/NECO (UG) or 2:1 (PG); age limits",url:S("Federal Scholarship Board Nigeria BEA scholarship"),ng:true,minClass:2,essays:["motivation"],tags:["nigeria","government"],national:true},
  {id:"nlng",name:"NLNG Undergraduate Scholarship",host:"Nigeria",region:"Nigeria",levels:["Undergraduate"],deadline:null,window:"Opens once a year (often late in the year); aptitude test",conf:"typical",funding:"Annual grant through first degree",elig:"100-level students in accredited Nigerian universities; strong UTME",url:"https://www.nigerialng.com/",ng:true,essays:[],tags:["nigeria","corporate"],national:true},
  {id:"total",name:"NNPC/TotalEnergies Scholarships",host:"Nigeria & France",region:"Nigeria",levels:["Undergraduate","Masters"],deadline:null,window:"National Merit (UG) and Master's abroad windows each year",conf:"typical",funding:"UG grant; MSc abroad fully funded",elig:"Nigerian; 2:1 within 5 years + NYSC for Master's",url:"https://totalenergies.ng/",ng:true,minClass:2,essays:["motivation"],tags:["nigeria","corporate","oil & gas"],national:true},
  {id:"agbami",name:"Agbami Medical & Engineering Scholarship",host:"Nigeria",region:"Nigeria",levels:["Undergraduate"],deadline:null,window:"Usually mid-year; for 2nd-year students",conf:"typical",funding:"Annual grant to graduation",elig:"200-level medicine or engineering students, Nigerian universities",url:S("Agbami scholarship Nigeria"),ng:true,essays:[],tags:["nigeria","corporate"],national:true},
  {id:"shell",name:"Shell / SNEPCo National University Scholarships",host:"Nigeria",region:"Nigeria",levels:["Undergraduate"],deadline:null,window:"Typically announced Q3–Q4; online test",conf:"typical",funding:"Annual grant",elig:"200-level students in public universities; merit (and operating-area) quotas",url:S("Shell Nigeria SNEPCo university scholarship"),ng:true,essays:[],tags:["nigeria","corporate","oil & gas"],national:true},
  {id:"seplat",name:"Seplat JV National University Scholarship",host:"Nigeria",region:"Nigeria",levels:["Undergraduate"],deadline:null,window:"Typically annual; aptitude test",conf:"typical",funding:"Annual grant",elig:"200-level+ students, federal/state universities",url:S("Seplat JV national undergraduate scholarship"),ng:true,essays:[],tags:["nigeria","corporate"],national:true},
  {id:"mtn",name:"MTN Foundation Science & Technology Scholarship",host:"Nigeria",region:"Nigeria",levels:["Undergraduate"],deadline:null,window:"Annual; STEM and visually-impaired streams",conf:"typical",funding:"Annual grant + internships",elig:"STEM undergrads with high CGPA in public tertiary institutions",url:S("MTN Foundation science and technology scholarship"),ng:true,essays:[],tags:["nigeria","corporate","stem"],national:true},
  {id:"ovia",name:"Jim Ovia Foundation Leaders Scholarship",host:"Nigeria",region:"Nigeria",levels:["Undergraduate"],deadline:null,window:"Annual intake",conf:"typical",funding:"Tuition + support",elig:"Nigerian undergraduates with leadership promise",url:S("Jim Ovia Foundation leaders scholarship"),ng:true,essays:["leadership"],tags:["nigeria","foundation"],national:true},
  {id:"nbplc",name:"Nigerian Breweries – Felix Ohiwerei Education Trust",host:"Nigeria",region:"Nigeria",levels:["Undergraduate"],deadline:null,window:"Annual",conf:"typical",funding:"Annual grant",elig:"Undergraduates in Nigerian universities; merit",url:S("Nigerian Breweries Felix Ohiwerei scholarship"),ng:true,essays:[],tags:["nigeria","corporate"],national:true},
  {id:"nddc",name:"NDDC Foreign Postgraduate Scholarship",host:"Abroad",region:"Nigeria",levels:["Masters","PhD"],deadline:null,window:"Irregular; watch official announcements",conf:"typical",funding:"Tuition + stipend",elig:"Indigenes of Niger Delta states; 2:1",url:S("NDDC foreign postgraduate scholarship"),ng:true,minClass:2,essays:["sop"],tags:["nigeria","regional"],national:true},
  {id:"tetfund",name:"TETFund AST&D (Academic Staff Training)",host:"Nigeria & abroad",region:"Nigeria",levels:["Masters","PhD"],deadline:null,window:"Through your institution's TETFund desk",conf:"typical",funding:"Tuition + allowances for staff of public tertiary institutions",elig:"Academic staff of TETFund-beneficiary institutions; bonding to return",url:"https://tetfund.gov.ng/",ng:true,essays:["proposal"],tags:["nigeria","staff"],national:true},
  {id:"nelfund",name:"NELFUND Student Loan",host:"Nigeria",region:"Nigeria",levels:["Undergraduate"],deadline:null,window:"Rolling portal",conf:"typical",funding:"Interest-free tuition & upkeep loan, repaid after NYSC/employment",elig:"Nigerian students in public tertiary institutions",url:"https://www.nelf.gov.ng/",ng:true,essays:[],tags:["nigeria","loan"],national:true},
  {id:"state",name:"State Government Scholarships (e.g. Lagos, Rivers, Akwa Ibom)",host:"Nigeria & abroad",region:"Nigeria",levels:["Undergraduate","Masters","PhD"],deadline:null,window:"Each state scholarship board sets its own",conf:"typical",funding:"Varies: bursary to full overseas scholarship",elig:"State of origin indigene; merit/need",url:S("state scholarship board Nigeria"),ng:true,essays:["motivation"],tags:["nigeria","government"],national:true}
];

/* Essay types: moves with cue patterns (regex source strings) */
window.LL_ESSAYS = {
  leadership:{name:"Leadership essay",for:"Chevening, Weidenfeld, SI, Schwarzman",limit:500,frame:"STAR",
    moves:[
      {k:"situation",label:"Situation",cue:"\\b(when|in 20\\d\\d|at (my|the)|as (a|the)|while working|during)\\b",tip:"Set the scene in one or two sentences: where, when, what was at stake.",weak:"I have been a leader in many places.",strong:"In 2023, as the only engineer at a 40-farmer cooperative in Benue, I saw 30% of our tomato harvest rot before reaching market."},
      {k:"action",label:"Your action",cue:"\\b(i (led|founded|organi[sz]ed|designed|launched|built|convinced|negotiated|mobili[sz]ed|trained|started|proposed|coordinated))\\b",tip:"Use 'I' + a strong verb. Show the decision you made, not the team's.",weak:"We worked together as a team to solve it.",strong:"I designed a solar-dried storage rack from scrap metal and trained 12 farmers to build their own."},
      {k:"obstacle",label:"Obstacle",cue:"\\b(but|however|resist|challenge|difficult|despite|opposed|sceptic|skeptic|setback|failed)\\b",tip:"Leadership shows under pressure. Name the resistance and how you handled it.",weak:"There were some challenges.",strong:"Elders doubted a 26-year-old outsider, so I ran a side-by-side trial on one plot first."},
      {k:"result",label:"Result",cue:"(\\d+\\s?%|\\d{2,}|increased|reduced|cut|saved|grew|doubled|halved|resulting|which led)",tip:"Quantify the outcome. Numbers make impact believable.",weak:"It was very successful.",strong:"Post-harvest loss fell from 30% to 9% in one season, adding ₦2.1m to members' income."},
      {k:"reflection",label:"Lesson & future",cue:"\\b(learn|taught me|realis|realiz|since then|now i|will|going forward|future)\\b",tip:"Close with what you learned and how you'll lead next — link to your plans.",weak:"I learned a lot.",strong:"I learned that trust is built with evidence, a lesson I will carry into leading Nigeria's cold-chain policy work."}
    ]},
  networking:{name:"Networking essay",for:"Chevening",limit:500,frame:"Give–Get–Grow",
    moves:[
      {k:"example",label:"Proof you network",cue:"\\b(connected|introduced|partnered|collaborat|met|reached out|built a network|joined)\\b",tip:"Give a real example of a relationship you built and what it produced.",weak:"I am a good networker and people like me.",strong:"I reached out to three NGOs after a webinar, which led to a joint water-testing project across 6 schools."},
      {k:"value",label:"Value you created",cue:"(\\d+|result|led to|enabled|helped|outcome|funding|grant)",tip:"Show the network produced something: a project, funding, a job, policy.",weak:"This helped a lot of people.",strong:"The partnership secured a £4,000 grant and tested water for 2,300 pupils."},
      {k:"uk",label:"UK network plan",cue:"\\b(uk|british|chevening|alumni|society|institution|association|london|cambridge|edinburgh)\\b",tip:"Name specific UK societies, labs, events, or people you'll connect with.",weak:"I will network with many people in the UK.",strong:"I will join the IWA UK Young Water Professionals and the Chevening Energy & Environment network."},
      {k:"future",label:"Long-term use",cue:"\\b(return|home|nigeria|future|will|long-term|sustain)\\b",tip:"Explain how the network will serve your career and country after you return.",weak:"I will use it in future.",strong:"On returning, I will use these links to co-found a Nigeria–UK wastewater reuse working group."}
    ]},
  whyuk:{name:"Why these UK courses",for:"Chevening",limit:500,frame:"Gap–Course–Fit",
    moves:[
      {k:"gap",label:"Your skills gap",cue:"\\b(lack|gap|need|without|limited|missing|to (deepen|gain|build))\\b",tip:"Start with what you can't yet do in your career.",weak:"I want to study abroad to gain knowledge.",strong:"My projects stall because I lack training in techno-economic assessment of treatment plants."},
      {k:"courses",label:"Three named courses",cue:"\\b(msc|ma|mres|llm|mba|university of|imperial|ucl|oxford|cambridge|edinburgh|manchester|leeds|module)\\b",tip:"Name all three courses and one module or lab that fills your gap.",weak:"UK universities are the best in the world.",strong:"Cranfield's MSc Water & Wastewater Engineering, especially its Resource Recovery module, fills this gap."},
      {k:"fit",label:"Why UK specifically",cue:"\\b(uk|britain|british|policy|industry|placement|regulator|ofwat|research)\\b",tip:"Point to UK practice you can learn from — policy, industry, placements.",weak:"The UK is a beautiful country.",strong:"The UK's nutrient-recovery pilots at Thames Water are the models Nigeria's utilities need."},
      {k:"use",label:"How you'll use it",cue:"\\b(return|apply|will|career|nigeria|home)\\b",tip:"Tie the skills back to your career plan.",weak:"This will help me.",strong:"I will apply these skills to scale the Makurdi reuse pilot within two years of returning."}
    ]},
  career:{name:"Career plan",for:"Chevening, Commonwealth, JJ/WBGSP",limit:500,frame:"Now–Next–Later",
    moves:[
      {k:"short",label:"Immediate goal",cue:"\\b(after (graduat|return)|immediate|first|short[- ]term|within (one|two|1|2) years?)\\b",tip:"Say exactly what role you will take on return, and where.",weak:"I will get a good job.",strong:"Within six months of returning I will lead the resource-recovery unit at a state water board."},
      {k:"long",label:"Long-term goal",cue:"\\b(long[- ]term|ten years|10 years|five years|5 years|eventually|by 20\\d\\d)\\b",tip:"Give a 5–10 year ambition with scale.",weak:"I want to become a big person in future.",strong:"By 2035 I aim to shape national wastewater-reuse regulations as a policy adviser."},
      {k:"bridge",label:"How the study bridges it",cue:"\\b(course|degree|msc|study|training|skills?)\\b",tip:"Connect the degree to each step of the plan.",weak:"The degree will help me.",strong:"The MSc gives me the modelling and policy tools that separate my current role from that goal."},
      {k:"impact",label:"Impact on country",cue:"(\\d+|communit|country|nigeria|people|million|sdg|policy)",tip:"Show who benefits and how much.",weak:"It will help my country.",strong:"Reuse standards could cut industrial freshwater demand in Lagos by 15%."}
    ]},
  personal:{name:"Personal statement",for:"Gates, Knight-Hennessy, Rhodes, admissions",limit:800,frame:"Hook–Journey–Future",
    moves:[
      {k:"hook",label:"Opening scene",cue:"^.{0,220}(\\b(i|my)\\b)",tip:"Open with a specific moment only you could write — no quotations, no 'since childhood'.",weak:"Ever since I was a child I have been passionate about science.",strong:"The borehole behind my grandmother's house in Gboko ran brown the week I turned twelve."},
      {k:"motivation",label:"Motivation",cue:"\\b(because|why|drove|drives|curious|question|wanted to understand|motivat)\\b",tip:"Explain what question or problem drives you.",weak:"I love engineering very much.",strong:"That week left me with a question: why could no one in town test what we were drinking?"},
      {k:"evidence",label:"What you've done",cue:"\\b(i (built|studied|researched|published|led|designed|taught|founded|analy[sz]ed|won))\\b",tip:"Two or three concrete achievements that show you acting on that question.",weak:"I have done many projects.",strong:"I built a ₦9,000 turbidity sensor for my final-year project and published the results."},
      {k:"why",label:"Why this programme",cue:"\\b(programme|program|professor|dr\\.?|lab|department|faculty|course|college)\\b",tip:"Name people, labs or resources that fit you.",weak:"Your university is world-class.",strong:"Prof. Adeyemi's low-cost sensing lab is where I can take this further."},
      {k:"future",label:"Future contribution",cue:"\\b(will|future|plan|aim|return|contribute|goal)\\b",tip:"End with a forward-looking commitment.",weak:"I hope to be successful.",strong:"I will return to build a testing network that gives every Benue community its own water data."}
    ]},
  sop:{name:"Statement of purpose (research)",for:"PhD & research master's",limit:1000,frame:"Question–Preparation–Fit",
    moves:[
      {k:"interest",label:"Research interest",cue:"\\b(research|interest|question|investigat|hypothes|focus)\\b",tip:"State the problem you want to work on in the first paragraph.",weak:"I want to do research in environmental engineering.",strong:"I want to understand how granule structure controls exopolysaccharide yield in aerobic granular sludge."},
      {k:"prep",label:"Preparation",cue:"\\b(thesis|dissertation|project|course(work)?|lab|method|data|model|analy)\\b",tip:"Show the methods and results you already have.",weak:"I have a strong background.",strong:"My MSc dissertation modelled EPS recovery using 18 months of plant data, achieving R² = 0.87."},
      {k:"fit",label:"Supervisor & lab fit",cue:"\\b(professor|prof\\.?|dr\\.?|lab|group|supervisor|work on|paper)\\b",tip:"Name a supervisor and one of their papers or projects.",weak:"Your faculty are excellent.",strong:"Dr Lin's 2024 work on alginate-like exopolymers directly informs my proposed methods."},
      {k:"goals",label:"Career goals",cue:"\\b(career|goal|academ|industry|future|plan|will)\\b",tip:"Say what this degree lets you do next.",weak:"I will become a professor.",strong:"I aim to lead a biorefinery research group advising Nigerian breweries on resource recovery."}
    ]},
  proposal:{name:"Research proposal",for:"Commonwealth PhD, MEXT, CSC, TETFund",limit:1500,frame:"Background–Gap–Aims–Methods–Impact",
    moves:[
      {k:"background",label:"Background",cue:"\\b(studies|literature|et al|has been|research shows|reported|according to|\\(\\d{4}\\))",tip:"Summarise what is known, with citations.",weak:"Water is very important for life.",strong:"AGS reactors recover up to 25% of sludge mass as exopolymers (Lin et al., 2010)."},
      {k:"gap",label:"Knowledge gap",cue:"\\b(however|gap|unknown|unclear|few studies|little is known|lack|remains)\\b",tip:"State precisely what is not yet known.",weak:"More research is needed.",strong:"However, no study has quantified curdlan-type β-1,3-glucans from AGS fed brewery wastewater."},
      {k:"aims",label:"Aims & questions",cue:"\\b(aim|objective|question|hypothes|this study will|rq\\d?)\\b",tip:"Give 1 aim and 2–4 numbered objectives or questions.",weak:"I will study the topic.",strong:"Aim: determine whether brewery-fed AGS yields extractable curdlan. RQ1: how does C/N ratio affect yield?"},
      {k:"methods",label:"Methods",cue:"\\b(method|sample|reactor|survey|interview|experiment|analysis|measure|model|design)\\b",tip:"Describe design, data, and analysis concretely.",weak:"I will use scientific methods.",strong:"Two 5 L SBRs will run at C/N 20 and 40; EPS will be extracted by alkaline-heat and quantified by aniline blue."},
      {k:"impact",label:"Significance",cue:"\\b(significan|impact|contribut|policy|benefit|industry|sdg)\\b",tip:"Explain who uses the findings.",weak:"This will be useful.",strong:"Results will give breweries a route to sell curdlan while cutting treatment costs."}
    ]},
  impact:{name:"Development impact statement",for:"Commonwealth, DAAD EPOS, Weidenfeld",limit:500,frame:"Problem–Plan–Proof",
    moves:[
      {k:"problem",label:"Development problem",cue:"(\\d+|%|million|lack|poverty|access|crisis|problem|challenge)",tip:"Quantify the problem in your country.",weak:"Nigeria has many problems.",strong:"Only 29% of Nigerians have access to safely managed drinking water."},
      {k:"plan",label:"Your plan",cue:"\\b(i will|plan|project|initiative|pilot|scale)\\b",tip:"Describe the concrete project you'll carry out.",weak:"I will help solve it.",strong:"I will pilot decentralised reuse units at two Benue markets."},
      {k:"sdg",label:"Link to SDGs / policy",cue:"\\b(sdg|goal \\d|policy|national|strategy|agenda)\\b",tip:"Anchor the plan in SDGs or national policy.",weak:"It is in line with global goals.",strong:"This supports SDG 6.3 and Nigeria's Partnership for Expanded WASH plan."},
      {k:"proof",label:"Track record",cue:"\\b(have|already|previously|since 20\\d\\d|led|founded|built)\\b",tip:"Show you've already started — credibility.",weak:"I am capable.",strong:"I have already mapped 14 discharge points with the state EPA."}
    ]},
  motivation:{name:"Motivation letter",for:"Erasmus Mundus, DAAD, Eiffel, Türkiye",limit:700,frame:"Why me–Why this–Why now",
    moves:[
      {k:"whome",label:"Who you are",cue:"\\b(i am|my background|graduated|degree|experience)\\b",tip:"Introduce your academic and professional profile briefly.",weak:"My name is John and I am applying.",strong:"I graduated First Class in Agricultural Engineering and have taught engineering materials for three years."},
      {k:"whythis",label:"Why this programme",cue:"\\b(programme|program|consortium|mobility|module|track|specialis|speciali[sz])\\b",tip:"Name the tracks, mobility path or modules you want.",weak:"This programme is very good.",strong:"The Delft–Lisbon mobility track matches my interest in circular water systems."},
      {k:"contribution",label:"What you bring",cue:"\\b(bring|contribute|offer|perspective|experience)\\b",tip:"Say what classmates gain from you.",weak:"I will be a good student.",strong:"I bring field data from West African smallholder systems that few cohorts have."},
      {k:"after",label:"After graduation",cue:"\\b(after|career|return|future|goal|plan)\\b",tip:"Close with a clear plan.",weak:"I will find something to do.",strong:"After graduating I will join a regional utility's reuse programme."}
    ]},
  argument:{name:"Argumentative academic essay",for:"Coursework, exams, writing tests",limit:1200,frame:"Thesis–Evidence–Counter–Rebut",
    moves:[
      {k:"thesis",label:"Thesis",cue:"\\b(this essay (argues|contends)|i argue|this paper|should|must|thesis)\\b",tip:"State a debatable claim in the introduction.",weak:"This essay will talk about renewable energy.",strong:"This essay argues that mini-grids, not grid extension, are the fastest route to rural electrification in Nigeria."},
      {k:"evidence",label:"Evidence",cue:"(\\(\\d{4}\\)|et al|according to|data|study|report|\\d+%|found that)",tip:"Support each point with a cited source or data.",weak:"Many people say solar is cheap.",strong:"IRENA (2023) reports solar mini-grid costs fell 65% between 2010 and 2022."},
      {k:"counter",label:"Counterargument",cue:"\\b(critics|opponents|some argue|however|on the other hand|although|admittedly)\\b",tip:"Present the strongest opposing view fairly.",weak:"Some people disagree.",strong:"Critics argue mini-grids fragment the market and raise tariffs."},
      {k:"rebut",label:"Rebuttal",cue:"\\b(yet|nevertheless|nonetheless|but this|this overlooks|in fact|evidence suggests)\\b",tip:"Answer the counterargument with evidence.",weak:"But they are wrong.",strong:"Yet this overlooks that tariff subsidies under the DARES programme bring costs close to grid rates."},
      {k:"conclusion",label:"Conclusion",cue:"\\b(in sum|overall|therefore|thus|to conclude|this essay has)\\b",tip:"Restate the thesis in light of the evidence and give an implication.",weak:"In conclusion, energy is important.",strong:"Therefore, policy should prioritise mini-grid licensing over costly grid extension."}
    ]},
  reflective:{name:"Reflective essay (Gibbs)",for:"Teaching, nursing, professional courses",limit:800,frame:"Gibbs cycle",
    moves:[
      {k:"description",label:"Description",cue:"\\b(happened|during|when|on (monday|tuesday|wednesday|thursday|friday)|in (week|class))\\b",tip:"What happened? Keep it brief and factual.",weak:"Something happened in class.",strong:"During week 4, my lab group's reactor failed two hours before the demonstration."},
      {k:"feelings",label:"Feelings",cue:"\\b(felt|feel|anxious|frustrat|excited|nervous|embarrass|relieved)\\b",tip:"How did you feel and think at the time?",weak:"It was bad.",strong:"I felt anxious because I had assured the team the pump was tested."},
      {k:"evaluation",label:"Evaluation",cue:"\\b(went well|went badly|positive|negative|worked|didn.?t work)\\b",tip:"What went well and what didn't?",weak:"Some things were good.",strong:"Our backup plan worked, but my testing log was incomplete."},
      {k:"analysis",label:"Analysis",cue:"\\b(because|theory|kolb|schön|schon|literature|explains|suggests)\\b",tip:"Make sense of it using theory or literature.",weak:"It happened because of bad luck.",strong:"Schön's reflection-in-action explains why improvising a gravity feed felt natural."},
      {k:"action",label:"Action plan",cue:"\\b(next time|in future|i will|plan to|going forward)\\b",tip:"What will you do differently?",weak:"I will do better.",strong:"Next time I will run a full pre-demo checklist 24 hours ahead."}
    ]},
  abstract:{name:"Research abstract",for:"Conferences, journals, posters",limit:250,frame:"IMRaD",
    moves:[
      {k:"bg",label:"Background",cue:"\\b(is|are|remains|critical|important|growing)\\b",tip:"One sentence of context.",weak:"Water is life.",strong:"Brewery wastewater is rich in carbohydrates that are rarely recovered."},
      {k:"aim",label:"Aim",cue:"\\b(this study|we|aim|objective|investigat|evaluat)\\b",tip:"One sentence on what you did and why.",weak:"We did some work.",strong:"This study evaluated curdlan recovery from AGS fed brewery wastewater."},
      {k:"method",label:"Method",cue:"\\b(using|were|was|sampled|measured|operated|analy)\\b",tip:"How — design, sample, analysis.",weak:"We used methods.",strong:"Two SBRs were operated for 120 days and EPS was extracted by alkaline heating."},
      {k:"results",label:"Results",cue:"(\\d+|%|increased|decreased|significant|p\\s?<)",tip:"Main findings with numbers.",weak:"The results were good.",strong:"Curdlan reached 112 mg/g VSS, 38% higher at C/N 40 (p < 0.05)."},
      {k:"concl",label:"Conclusion",cue:"\\b(suggest|indicate|demonstrat|conclude|implication|potential)\\b",tip:"What the results mean.",weak:"This is useful.",strong:"Brewery-fed AGS is a viable curdlan source for circular biorefineries."}
    ]}
};

window.LL_CLICHES = ["ever since i was","since i was a child","from a young age","since childhood","passionate about","i have always wanted","make the world a better place","dream come true","hardworking","hard-working","since time immemorial","in today's world","in this modern world","in this contemporary world","last but not least","at the end of the day","think outside the box","go-getter","team player","i believe that","needless to say","it goes without saying","in a nutshell","a lot of","very unique","webster","dictionary defines","i am writing to apply","my name is","world-class","second to none","burning desire","humbly","i am a fast learner","each and every","first and foremost","the likes of","ample opportunity"];
window.LL_FILLER = ["very","really","basically","actually","just","things","stuff","etc","somehow","quite","extremely","in order to","due to the fact that","various","numerous"];
window.LL_STRONGVERBS = ["led","founded","co-founded","designed","launched","built","created","secured","raised","reduced","increased","cut","doubled","trained","mentored","negotiated","organised","organized","coordinated","published","analysed","analyzed","developed","won","delivered","implemented","piloted","mobilised","mobilized","initiated","established","managed","taught","wrote","presented","modelled","modeled","convinced","scaled","tested","surveyed","mapped","drafted"];

window.LL_GAME_SENTENCES = [
  ["Ever since I was a child, I have been passionate about helping people.",false,"Cliché opener + vague 'helping people'."],
  ["In 2022 I trained 45 secondary-school girls in Makurdi to code their first Arduino project.",true,"Date, place, number, strong verb."],
  ["I am a hardworking team player who thinks outside the box.",false,"Three clichés, zero evidence."],
  ["My pilot cut diesel costs at the clinic by 38% in six months.",true,"Quantified result with timeframe."],
  ["Nigeria is a country with many problems that need to be solved.",false,"Generic; any applicant could write this."],
  ["When the cooperative's chairman opposed the plan, I ran a two-plot trial to show the numbers.",true,"Obstacle + action + evidence."],
  ["The UK is the best place in the world to study.",false,"Unsupported superlative."],
  ["Cranfield's Resource Recovery module fills the exact modelling gap that stalls my projects.",true,"Specific course link to a stated gap."],
  ["I believe that I will be a great asset to your esteemed institution.",false,"Hedge + flattery; no proof."],
  ["I reached out to the state EPA, which led to a joint survey of 14 discharge points.",true,"Networking with concrete outcome."],
  ["There were a lot of challenges but we overcame them.",false,"Vague — name the challenge."],
  ["Within two years of returning I will lead the reuse unit at Benue State Water Board.",true,"Named role, place and timeframe."],
  ["Education is the key to success, as the saying goes.",false,"Proverb opener; empty."],
  ["I secured a ₦1.2m grant from the Tony Elumelu Foundation to scale the dryer to three villages.",true,"Named funder, amount, scale."],
  ["I humbly request that you consider my application favourably.",false,"Formulaic; spend words on evidence."],
  ["My dissertation modelled EPS recovery from 18 months of plant data (R² = 0.87).",true,"Method + data + metric."]
];

window.LL_ORDER_GAME = {
  title:"Rebuild a leadership essay (STAR)",
  parts:[
    "In 2023 I was the only engineer at a 40-farmer cooperative in Benue, where 30% of our tomatoes rotted before reaching market.",
    "I designed a solar-dried storage rack from scrap metal and trained 12 farmers to build their own.",
    "The elders doubted a 26-year-old outsider, so I ran a side-by-side trial on one plot to let the results speak.",
    "Losses fell from 30% to 9% in one season, adding ₦2.1m to members' income.",
    "I learned that trust is earned with evidence — a lesson I will bring to leading cold-chain policy work in Nigeria."
  ],
  labels:["Situation","Action","Obstacle","Result","Reflection"]
};

window.LL_REWRITES = [
  {weak:"I am passionate about renewable energy.",hint:"Replace the feeling with something you did: verb + number + place."},
  {weak:"I have a lot of leadership experience.",hint:"Name one role, a team size, and one result."},
  {weak:"I want to study in the UK because it has good universities.",hint:"Name a course or module and the skill gap it fills."},
  {weak:"My project was very successful.",hint:"Quantify: %, ₦, people, time."},
  {weak:"I will help my country when I return.",hint:"Say which role, organisation, and by when."}
];

window.LL_INTERVIEW = {
  Chevening:["Tell us about yourself in two minutes.","Describe a time you led a team through resistance.","Why did you choose these three UK courses?","How will you use your Chevening network after you return?","Where do you see yourself 10 years after your degree?","What will you do if you don't get the scholarship?","Describe a time you failed. What did you learn?","How does your plan address a national priority in Nigeria?"],
  Commonwealth:["How will your study contribute to development in your country?","What is the biggest barrier to your plan, and how will you handle it?","How will your research be used by policymakers?","Why is this UK institution the right one?"],
  Rhodes:["What is a belief you have changed your mind about?","If you could fix one global problem, which and how?","Defend a position that most of your friends disagree with.","How do you define leadership that serves others?"],
  Fulbright:["How will you act as a cultural ambassador in the U.S.?","Why must this study happen in the U.S.?","How will you share what you learn when you return?","What do Americans misunderstand about Nigeria?"],
  PhD:["Summarise your research proposal in one minute.","Why is this question important now?","What happens if your main hypothesis is wrong?","Which of my papers is most relevant to your work, and why?","What will your first-year milestones be?"]
};

window.LL_PATHWAYS = [
  {t:"Government scholarships",d:"Chevening, Commonwealth, Fulbright, MEXT, GKS, CSC, Türkiye, BEA.",steps:["List 5 whose home country list includes yours","Mark deadlines 3 months early in the planner","Draft the essays in the Essay Dojo","Line up 2 referees 6 weeks ahead"]},
  {t:"University merit awards",d:"Automatic or separate awards: Clarendon, Gates, KTH, Delft, ETH.",steps:["Apply before the course's funding deadline — often earlier than the admission deadline","Check 'consider me for funding' boxes","Upload strongest transcript + CV"]},
  {t:"Funded PhD via a supervisor",d:"Many PhDs are paid from a professor's grant — no scholarship form at all.",steps:["Find 10 professors who published on your topic in the last 3 years","Send a short tailored email (use the Cold-email builder)","Attach 1-page CV + 1-page research idea","Follow up once after 10 days"]},
  {t:"Research & teaching assistantships",d:"US/Canada grad schools pay tuition + stipend for RA/TA work.",steps:["Look for 'guaranteed funding' on department pages","Mention TA-able courses in your SOP","Prepare for a teaching-English check (TOEFL speaking)"]},
  {t:"Foundations & fellowships",d:"Mastercard, AAUW, Aga Khan, Heinrich Böll, Konrad Adenauer, Ford-type fellowships.",steps:["Match mission to your story","Many need need-based evidence — gather documents","Track their annual cycles in the tracker"]},
  {t:"Employer / institution sponsorship",d:"TETFund AST&D, company study leave, ministry training budgets.",steps:["Ask HR/TETFund desk about the bonding terms","Get an admission offer first","Negotiate study leave with pay"]},
  {t:"Corporate CSR scholarships",d:"NLNG, TotalEnergies, Shell/SNEPCo, Seplat, MTN, Agbami.",steps:["Watch official pages and verified socials","Practise aptitude tests (numerical + verbal)","Never pay to 'unlock' a form"]},
  {t:"Student loans",d:"NELFUND (Nigeria), MPOWER & Prodigy (no-cosigner international loans).",steps:["Compare interest and repayment triggers","Borrow only the funding gap","Use the Gap calculator first"]},
  {t:"Exchanges & short programmes",d:"Erasmus+ ICM, summer schools, research visits, Mitacs Globalink.",steps:["Ask your department's international office","Short stays build networks for later PhD offers"]},
  {t:"Travel & conference grants",d:"Societies (IWA, IEEE, RSC) fund student travel and posters.",steps:["Submit an abstract (practise in the Abstract dojo)","Apply for the society's student bursary at the same time"]},
  {t:"Competitions & prizes",d:"Essay contests, hackathons, pitch competitions pay fees and build your CV.",steps:["Enter 1 per semester","Reuse winning work in scholarship essays"]},
  {t:"Crowdfunding, diaspora & alumni",d:"Alumni associations, church/community funds, GoFundMe for the final gap.",steps:["Write a 150-word impact story","Share a budget breakdown for trust","Give updates to donors"]}
];

/* ---------- v2 additions (29 Sep 2026): fields of study, per-award requirements ---------- */
window.LL_FIELDS = ["Engineering & technology", "Natural sciences", "Health & medicine", "Agriculture & environment", "Business & economics", "Social sciences & development", "Law & policy", "Energy, oil & gas", "Education", "Arts & humanities"];
(function () {
  const F = window.LL_FIELDS, byId = {};
  window.LL_SCHOLARSHIPS.forEach((s) => (byId[s.id] = s));
  const DEV = ["Agriculture & environment", "Social sciences & development", "Engineering & technology", "Health & medicine", "Business & economics", "Education", "Law & policy"];
  const STEM = ["Engineering & technology", "Natural sciences"];
  const fields = {
    "daad-epos": DEV, jjwbgsp: DEV,
    kth: STEM, delft: STEM, eth: STEM.concat(["Agriculture & environment"]),
    ptdf: ["Engineering & technology", "Natural sciences", "Energy, oil & gas", "Business & economics", "Law & policy"],
    nlng: ["Engineering & technology", "Natural sciences", "Health & medicine", "Business & economics"],
    total: ["Engineering & technology", "Natural sciences", "Energy, oil & gas", "Business & economics"],
    agbami: ["Engineering & technology", "Health & medicine"],
    mtn: ["Engineering & technology", "Natural sciences", "Health & medicine"],
    shell: ["Engineering & technology", "Natural sciences", "Energy, oil & gas", "Business & economics"],
    seplat: ["Engineering & technology", "Natural sciences", "Energy, oil & gas", "Business & economics", "Health & medicine"],
    tetfund: F.slice(), nelfund: F.slice()
  };
  window.LL_SCHOLARSHIPS.forEach((s) => { s.fields = fields[s.id] || null; /* null = open to any field */ });

  /* Requirements: src "official" = read from the funder's page on 29 Sep 2026; "typical" = common for this award, confirm */
  const R = {
    chevening: { src: "official", items: ["Undergraduate degree that qualifies you for a UK master's, completed at least 2 years before the deadline", "At least 2 years' work experience after your degree (2,800 hours)", "Apply to 3 different eligible UK master's courses", "Unconditional offer from one of the 3 courses by the deadline on the Chevening timeline", "Commit to return home for at least 2 years after the award", "4 essays: leadership, networking, why these UK courses, career plan (check word limits in the form)", "2 references (requested after you apply)", "English is assessed by your universities, not by Chevening"] },
    "csc-masters": { src: "official", items: ["First degree at 2:1 or above, or a 2:2 plus a relevant postgraduate qualification", "Apply through your national nominating body first (Nigeria: Federal Scholarship Board); it sets its own earlier deadline", "Valid passport or national ID", "Complete transcripts (certified English translation if needed)", "At least 2 references: signed PDF on letterhead or official email; one from your employer if employed", "Development impact statement (4 parts: the issue, skills you'll apply, expected outcomes with timeframe, how you'll measure them)", "Personal statement, leadership and voluntary activities summary, study plan", "No IELTS required by the CSC (your university may still require one)"] },
    "csc-phd": { src: "typical", items: ["Apply through your national nominating body first", "Research proposal (Dojo: Research proposal)", "Supporting statement from a UK supervisor usually expected", "At least 2 references", "Transcripts and certificates"] },
    gates: { src: "official", items: ["Apply to a full-time Cambridge postgraduate course and tick Gates Cambridge in the same application", "Gates statement: 4 answers — Q1 & Q2 ≈200 words (1,400 characters), Q3 & Q4 ≈300 words (2,100 characters)", "3 references: 2 academic (for admission) + 1 Gates Cambridge reference on the scholarship criteria", "PhD applicants: research proposal with the course application"] },
    knight: { src: "official", items: ["Bachelor's degree earned in January 2020 or later (2018 or later with military service)", "Separate application to a full-time Stanford graduate programme starting the same year", "Résumé, transcripts and test scores as your Stanford programme requires", "Short answers, essay and recommendations (see the Knight-Hennessy application for counts)", "Video statement if invited"] },
    ptdf: { src: "official", items: ["MSc: 2:1, or 2:2 with relevant industry experience · PhD: at least 2:2 plus a good master's", "NYSC discharge certificate", "First degree certificate or statement of result", "WAEC/NECO/GCE results with PINs", "Local government identification letter", "Recent passport photograph", "Professional association membership evidence", "MSc: statement of purpose, max 500 words", "PhD: oil & gas research proposal, max 5 pages", "Online screening test if shortlisted"] },
    schwarzman: { src: "official", items: ["Age 18–28 on 1 August of the enrolment year", "Bachelor's degree by the start of the programme", "Leadership record"] },
    "rhodes-wa": { src: "typical", items: ["Age limits apply — see the Information for Candidates document", "Personal statement and academic statement", "Several referees (check the document for the number)", "Must meet Oxford course entry requirements"] }
  };
  window.LL_SCHOLARSHIPS.forEach((s) => {
    const own = R[s.id];
    const derived = [];
    if (s.ageMax) derived.push(`Age limit: around ${s.ageMax} or younger (check exact date rule)`);
    if (s.workHrs) derived.push(`Work experience: about ${s.workHrs.toLocaleString()} hours (${Math.round(s.workHrs / 1800 * 10) / 10}+ years full-time)`);
    if (s.minClass) derived.push(["", "Usually expects a First Class or equivalent", "Usually expects a 2:1 or equivalent", "Usually expects a 2:2 or better"][s.minClass]);
    const typical = s.levels.includes("Undergraduate") && !s.levels.includes("Masters")
      ? ["Secondary-school results (WAEC/NECO) or current transcripts", "Admission letter / matriculation number where required", "Passport photograph and valid ID"]
      : ["Passport valid at least 12 months beyond your start date (check the host country's visa rule)", "Transcripts and degree certificate", "2-page CV", "English test if the university asks — commonly IELTS 6.5 overall with no band below 6.0, or TOEFL/PTE/Duolingo equivalent", "2–3 referees"];
    s.req = own ? { src: own.src, items: own.items } : { src: "typical", items: derived.concat(typical) };
  });
  byId.chevening.elig = "Undergraduate degree that qualifies you for a UK master's, 2,800+ hours work experience, 3 UK course choices, return home for 2 years";
  delete byId.chevening.minClass;
  byId["csc-masters"].elig = "2:1 (or 2:2 plus a relevant postgraduate qualification); apply via your national nominating body (Nigeria: Federal Scholarship Board) and the CSC portal";

  const models = ["In 2023 I installed solar dryers for 12 women farmers in Makurdi, cutting diesel use by 40%.", "As president of the NSE student chapter, I led 35 volunteers to run a STEM fair for 600 pupils.", "Cranfield's MSc Energy Systems teaches the grid-modelling skills my Kaduna mini-grid projects lack.", "The pilot cut tomato losses from 30% to 9% and added ₦2.1m to 40 farmers' income in one season.", "Within two years of returning I will lead the off-grid unit at the Rural Electrification Agency in Abuja."];
  window.LL_REWRITES.forEach((r, i) => (r.model = models[i]));
})();

/* ---------- v3 corrections (7 Oct 2026): checked against official pages while writing the step-by-step guides ---------- */
(function () {
  const by = {}; window.LL_SCHOLARSHIPS.forEach((s) => (by[s.id] = s));
  const P = (id, o) => { if (by[id]) Object.assign(by[id], o); };
  window.LL_CHECKED = "2026-10-07";
  P("chevening", { window: "2027/28 round closed 6 Oct 2026 · next round usually opens early Aug 2027" });
  P("knight", { window: "2027 cohort closed 6 Oct 2026 · 2028 cohort opens summer 2027" });
  P("csc-masters", { elig: "First degree at 2:1 or above; Commonwealth citizen of an eligible country; apply via your national nominating body (Nigeria: Federal Scholarship Board) and the CSC portal" });
  P("csc-phd", { conf: "confirmed", window: "Closes 20 Oct 2026, 16:00 UK time — national nominator deadline may be earlier", elig: "Citizen of one of 17 eligible countries (Nigeria included); 2:1, or 2:2 plus a relevant master's; research proposal with UK supervisor statement" });
  P("fulbright", { levels: ["PhD"], deadline: "2027-06-01", window: "Call usually posted ~March; closes ~1 June 2027", elig: "PhD students already enrolled at a Nigerian university; non-degree visiting-researcher stay in the U.S.; TOEFL 90+", funding: "Stipend, airfare, health cover for a research stay" });
  P("aauw", { deadline: "2026-09-17", conf: "confirmed", window: "2027–28 round ran 17 Aug – 17 Sep 2026 (closed) · next round expected Aug–Sep 2027", funding: "US$20,000 (master's) or US$25,000 (doctorate)", elig: "Women who are not U.S. citizens, studying STEM, GPA 3.5/4.0+, already admitted to a U.S. programme" });
  P("mext", { deadline: "2027-06-08", window: "Nigeria: hard-copy application to the Embassy of Japan, Abuja · 2027 call closed 8 Jun 2026 · expect May–Jun 2027", elig: "Apply via the Embassy of Japan in Nigeria; age limits apply (research students: born on or after 2 Apr 1992 in the last round)" });
  P("jjwbgsp", { deadline: "2027-02-26", conf: "confirmed", window: "Window 1: 18 Jan – 26 Feb 2027 · Window 2: 29 Mar – 21 May 2027 (noon EST)", elig: "3+ years' development-related work after first degree; unconditional admission to an eligible programme when you apply" });
  P("mandela-rhodes", { deadline: "2026-04-14", window: "2027 round closed 14 Apr 2026 · 2028 round opens 9 Mar 2027" });
  P("eth", { deadline: "2026-11-30", conf: "confirmed", window: "1–30 Nov 2026 with your master's application (closes 11:59 CET — submit by 28 Nov)", funding: "CHF 13,500/semester + tuition waiver" });
  P("radboud", { funding: "Tuition reduced to about €2,771 (to be confirmed); living costs not covered", window: "31 Jan 2027 · file complete (incl. English test) by 14 Feb 2027" });
  P("eiffel", { funding: "€1,200/month (master's), €2,100 (PhD), travel, insurance", elig: "Apply through a French host institution; master's applicants 29 or younger, PhD 35 or younger" });
  P("ubc-isp", { window: "15 Nov 2026 for international applicants" });
  P("fsb-bea", { conf: "closed", deadline: null, window: "No 2026/27 or 2027/28 round — new BEA awards suspended in May 2025 for five years", url: "https://education.gov.ng/federal-scholarships-board/" });
  P("ptdf", { elig: "Nigerian; oil & gas-relevant fields; 2:1 (or 2:2 with industry experience) for MSc, 2:2 + good MSc for PhD; NYSC; zonal interview if shortlisted" });
  P("nlng", { window: "Once a year, recently mid-Nov to mid-Dec · online proctored test", elig: "First-year students at federal or state universities; 5 O'Level credits in one sitting; UTME 200+; age 18–25", url: "https://www.nigerialng.com/csr/Pages/Scholarships.aspx" });
  P("total", { url: "https://csr-ngscholarship.totalenergies.com/", window: "Master's in France: usually closes ~31 Jan · Undergraduate (NMSS): mid-year" });
  P("agbami", { window: "No round confirmed since 2021/22 — watch for an official advert", url: "https://www.chevron.com/worldwide/nigeria" });
  P("nddc", { levels: ["Masters"], window: "2026/27 round ran 23 Mar – 19 Apr 2026, then CBT + interview · expect ~Mar–Apr 2027", elig: "Indigenes of the nine Niger Delta states; First or 2:1; under 40; NYSC; overseas admission letter", url: "https://www.nddc.gov.ng/" });
  P("tetfund", { elig: "Academic staff of TETFund-beneficiary public institutions; study at Nigerian universities (foreign awards suspended since 1 Jan 2025); bonded to return" });
  P("nelfund", { elig: "Nigerian students in public tertiary institutions and approved vocational schools", funding: "Interest-free loan for fees, plus upkeep, repaid after NYSC/employment" });
  P("nbplc", { window: "No open public application found for 2025–27", elig: "Awards so far by recognition, not open application — prepare alternatives", url: "https://www.nbplc.com/tag/education/" });
  P("ovia", { essays: [], window: "Form opens for only a few days between Oct and Dec (26–28 Nov in 2025)", url: "https://jimoviafoundation.org/faq/" });
  P("shell", { elig: "200-level students in public universities; CGPA 3.5+; computer-based test (NNPC/SNEPCo award)", url: "https://www.shell.com.ng/sustainability/communities/education-programmes.html" });
  P("seplat", { url: "https://www.seplatenergy.com/news-insights/news/nnpcseplat-jv-national-undergraduate-scholarship/", window: "Short annual window (23 Feb – 13 Mar in 2026) · aptitude test" });
  P("mtn", { url: "https://www.mtn.ng/scholarships/", window: "Annual, about April–May (2026 round closed 31 May)" });
  P("delft", { funding: "Full tuition + contribution to living expenses", elig: "Excellent non-EU MSc applicant; 35 or younger on 1 Sep; Nigeria: 5-year bachelor's with First or 2:1" });
  P("kth", { window: "Scholarship form 1 Dec 2026 – 15 Jan 2027 · results 1 Apr 2027", conf: "confirmed" });
  /* the guided step-by-step walkthroughs live in /laureate/guides/<id>.json and load on demand */
  window.LL_GUIDED = window.LL_SCHOLARSHIPS.map((s) => s.id);
})();
